### ISSUE TITLE
defaultInitialNodes appears to be ignored

### ISSUE THREAD

**Issue by justusranvier** [DanielKrawisz/bmd#7]
When starting bmd for the first time with --nodnsseed, bmd should boostrap using the list of peers in defaultInitialNodes. however it never attempts to connect to any of them.

**Comment by DanielKrawisz** [comment]
Fixed! https://github.com/DanielKrawisz/bmd/commit/7d114c25c4daf5660d51bf17f62b2ff16fbf5168
